In [2]:
import numpy as np

In [9]:
a3=np.array([
    [[1,2,3],[4,5,6]],
            [[7,8,9],[10,11,12]]
            ])
print(a3.ndim)
print(a3.shape)

3
(2, 2, 3)


In [10]:
a3[:]

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [11]:
a3[:,-1:]    # row indexing or element indexing

array([[[ 4,  5,  6]],

       [[10, 11, 12]]])

In [13]:
a3[:,-1:,2:]

array([[[ 6]],

       [[12]]])

In [27]:
a3[:,0,1]

array([2, 8])

In [29]:
a3[:,0]

array([[1, 2, 3],
       [7, 8, 9]])

In [31]:
a3[:,1:2:2]

array([[[ 4,  5,  6]],

       [[10, 11, 12]]])

In [32]:
a=np.array([1,2,3,4])
print(a)

[1 2 3 4]


In [34]:
a1=np.arange(1,21)
a1

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [39]:
a1.size

20

In [42]:
g=a1.reshape(4,5)
g

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20]])

In [44]:
g.ndim

2

In [48]:
a1=a1.reshape(2,5,2)
a1

array([[[ 1,  2],
        [ 3,  4],
        [ 5,  6],
        [ 7,  8],
        [ 9, 10]],

       [[11, 12],
        [13, 14],
        [15, 16],
        [17, 18],
        [19, 20]]])

In [49]:
a1.ndim

3

In [50]:
a1.reshape(4,-1)

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20]])

In [53]:
a1.reshape(-1,4)

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16],
       [17, 18, 19, 20]])

In [55]:
a1.reshape(4,5)

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20]])

In [63]:
a1.reshape(-2,4,5)

array([[[ 1,  2,  3,  4,  5],
        [ 6,  7,  8,  9, 10],
        [11, 12, 13, 14, 15],
        [16, 17, 18, 19, 20]]])

In [66]:
k=a1.reshape(4,5)
k

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20]])

In [67]:
k=np.transpose(k)
k

array([[ 1,  6, 11, 16],
       [ 2,  7, 12, 17],
       [ 3,  8, 13, 18],
       [ 4,  9, 14, 19],
       [ 5, 10, 15, 20]])

In [68]:
k.T

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20]])

In [69]:
k

array([[ 1,  6, 11, 16],
       [ 2,  7, 12, 17],
       [ 3,  8, 13, 18],
       [ 4,  9, 14, 19],
       [ 5, 10, 15, 20]])

In [71]:
a1=k.ravel()
a1

array([ 1,  6, 11, 16,  2,  7, 12, 17,  3,  8, 13, 18,  4,  9, 14, 19,  5,
       10, 15, 20])

In [72]:
a1

array([ 1,  6, 11, 16,  2,  7, 12, 17,  3,  8, 13, 18,  4,  9, 14, 19,  5,
       10, 15, 20])

In [74]:
np.insert(a1,3,65)

array([ 1,  6, 11, 65, 16,  2,  7, 12, 17,  3,  8, 13, 18,  4,  9, 14, 19,
        5, 10, 15, 20])

In [75]:
a1

array([ 1,  6, 11, 16,  2,  7, 12, 17,  3,  8, 13, 18,  4,  9, 14, 19,  5,
       10, 15, 20])

In [76]:
np.delete(a1,[7])

array([ 1,  6, 11, 16,  2,  7, 12,  3,  8, 13, 18,  4,  9, 14, 19,  5, 10,
       15, 20])

In [80]:
x=np.array([1,2,3])
y=np.array([4,5,6])

x,y

(array([1, 2, 3]), array([4, 5, 6]))

In [81]:
np.concatenate((x,y),axis=0)     #axis=0 is for row,   axis =1 is for column

array([1, 2, 3, 4, 5, 6])

In [83]:
x1=np.array([[1,2,3],[4,5,6]])
y1=np.array([[7,8,9],[10,11,12]])
x1,y1

(array([[1, 2, 3],
        [4, 5, 6]]),
 array([[ 7,  8,  9],
        [10, 11, 12]]))

In [87]:
np.concatenate((x1,y1),axis=1)    # concntenate columnwise

array([[ 1,  2,  3,  7,  8,  9],
       [ 4,  5,  6, 10, 11, 12]])

In [88]:
np.concatenate((x1,y1),axis=0)       # con cantate rowwise

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [92]:
# array manuplation
np.vstack((x,y1))    # stacke vertically(rowwise)

array([[ 1,  2,  3],
       [ 7,  8,  9],
       [10, 11, 12]])

In [93]:
np.hstack((x1,y1))   # stacks horizontally)(columnwise)

array([[ 1,  2,  3,  7,  8,  9],
       [ 4,  5,  6, 10, 11, 12]])

In [99]:
np.r_[x1,y1]

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [112]:
np.c_[x,y]

array([[1, 4],
       [2, 5],
       [3, 6]])

In [114]:
np.r_[x,y]

array([1, 2, 3, 4, 5, 6])

In [104]:
np.c_[x,y]

array([[1, 4],
       [2, 5],
       [3, 6]])

In [107]:
np.column_stack((x,y))

array([[1, 4],
       [2, 5],
       [3, 6]])

In [108]:
np.row_stack((x,y))

array([[1, 2, 3],
       [4, 5, 6]])

In [115]:
np.info(np.r_)

Translates slice objects to concatenation along the first axis.

This is a simple way to build up arrays quickly. There are two use cases.

1. If the index expression contains comma separated arrays, then stack
   them along their first axis.
2. If the index expression contains slice notation or scalars then create
   a 1-D array with a range indicated by the slice notation.

If slice notation is used, the syntax ``start:stop:step`` is equivalent
to ``np.arange(start, stop, step)`` inside of the brackets. However, if
``step`` is an imaginary number (i.e. 100j) then its integer portion is
interpreted as a number-of-points desired and the start and stop are
inclusive. In other words ``start:stop:stepj`` is interpreted as
``np.linspace(start, stop, step, endpoint=1)`` inside of the brackets.
After expansion of slice notation, all comma separated sequences are
concatenated together.

Optional character strings placed as the first element of the index
expression can be used to change the ou

In [ ]:
a=[1,2,3,4]

In [126]:
np.hsplit(a,4)

[array([1]), array([2]), array([3]), array([4])]

In [127]:
np.vsplit(y1,2)

[array([[7, 8, 9]]), array([[10, 11, 12]])]

In [129]:
np.hsplit(a,4)

[array([1]), array([2]), array([3]), array([4])]

In [116]:
#aggergate function
a.sum()

10

In [117]:
a.min() ,a.max()

(1, 4)

In [118]:
a.cumsum()   #cumsum= 1,1+2=3, 3+3=6,6+4=10

array([ 1,  3,  6, 10], dtype=int32)

In [119]:
a

array([1, 2, 3, 4])

In [120]:
a.mean()

2.5

In [123]:
np.median(a)

2.5

In [124]:
np.std(a)     # standard deviation

1.118033988749895

In [125]:
np.corrcoef(a)

1.0

In [130]:
np.var(a)       # variance

1.25

In [131]:
np.average(a)

2.5

In [132]:
y1

array([[ 7,  8,  9],
       [10, 11, 12]])

In [133]:
np.sum(y1,1)    # for rows

array([24, 33])

In [134]:
np.sum(y1,0) for columns

array([17, 19, 21])

In [135]:
np.argmin(y1)    # argument index

0

In [136]:
np.argmax(y1)

5

In [137]:
np.argmin(y1,1)

array([0, 0], dtype=int64)

In [140]:
np.argmin(y1,0)

array([0, 0, 0], dtype=int64)

In [143]:
a

array([1, 2, 3, 4])

In [144]:
# iterations for arrays
for x in a:
    print(x,end=" ")

1 2 3 4 

In [145]:
y1

array([[ 7,  8,  9],
       [10, 11, 12]])

In [146]:
for x in y1:
    for y in x:
        print(y,end=" ")

7 8 9 10 11 12 

In [147]:
a3

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [148]:
for x in a3:
    for y in x:
        for z in y:
            print(z,end=' ')

1 2 3 4 5 6 7 8 9 10 11 12 

In [149]:
# np.nditer    keyword for array iterarion
for x in np.nditer(a3):
    print(x,end=" ")

1 2 3 4 5 6 7 8 9 10 11 12 

In [150]:
a

array([1, 2, 3, 4])

In [151]:
np.sqrt(a)

array([1.        , 1.41421356, 1.73205081, 2.        ])

In [152]:
np.cos(a)

array([ 0.54030231, -0.41614684, -0.9899925 , -0.65364362])

In [153]:
np.sin(a)

array([ 0.84147098,  0.90929743,  0.14112001, -0.7568025 ])

In [154]:
np.tan(a)

array([ 1.55740772, -2.18503986, -0.14254654,  1.15782128])

In [155]:
np.exp(a)

array([ 2.71828183,  7.3890561 , 20.08553692, 54.59815003])

In [156]:
np.log(a)

array([0.        , 0.69314718, 1.09861229, 1.38629436])

In [157]:
np.log10(a)

array([0.        , 0.30103   , 0.47712125, 0.60205999])

In [159]:
np.log2(a)

array([0.       , 1.       , 1.5849625, 2.       ])

In [160]:
np.remainder(a,2)

array([1, 0, 1, 0], dtype=int32)

In [163]:
np.degrees(a)

array([ 57.29577951, 114.59155903, 171.88733854, 229.18311805])

In [164]:
np.diff(a)

array([1, 1, 1])

In [167]:
np.ediff1d(a3)   # conberts the array into 1-d array and calculate concestive  differance of each element

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1])

In [172]:
np.i0(a3)  # bessel function

array([[[1.26606588e+00, 2.27958530e+00, 4.88079259e+00],
        [1.13019220e+01, 2.72398718e+01, 6.72344070e+01]],

       [[1.68593909e+02, 4.27564116e+02, 1.09358835e+03],
        [2.81571663e+03, 7.28848934e+03, 1.89489253e+04]]])

In [173]:
np.power(a,2)

array([ 1,  4,  9, 16], dtype=int32)

In [175]:
np.mod(a,3)

array([1, 2, 0, 1], dtype=int32)

In [177]:
np.multiply(a,3)

array([ 3,  6,  9, 12])

In [179]:
np.divide(a,2)

array([0.5, 1. , 1.5, 2. ])

In [181]:
np.reciprocal(a,dtype=float)

array([1.        , 0.5       , 0.33333333, 0.25      ])

In [182]:
np.reciprocal(a)

array([1, 0, 0, 0], dtype=int32)

In [184]:
aj=np.array([1+2j,2+3j,3+4j])

In [185]:
np.real(aj)

array([1., 2., 3.])

In [187]:
np.imag(aj)

array([2., 3., 4.])

In [188]:
np.ravel(a3)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [191]:
a3.flatten()

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [192]:
a3.ravel()

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [196]:
np.random.rand()

0.6282622322591774

In [197]:
np.random.rand(1,2)

array([[0.23145947, 0.4630104 ]])

In [200]:
np.random.randint(150)

6

In [201]:
np.dot(x,y)

array([120, 132, 144])