
#### NumPy:
-      NumPy is a python library used for numerical data like working with arrays.
-      it consists of Scientific data calculations, Linear algebra, matrices etc

In [1]:
import numpy as np

In [4]:
# 1d array
s=np.array([1,2,3,4,5])
print(s)

[1 2 3 4 5]


In [7]:
s=[1,2,3,4,5,6]
d=np.size(s)
print(d)

6


In [12]:
a=[1,2,3,4,5,6]
b=np.array(a)
b.dtype

dtype('int32')

In [13]:
b.nbytes

24

In [14]:
b.itemsize

4

In [15]:
b.shape

(6,)

In [16]:
b.ndim

1

In [17]:
b = np.array([1,23,45,"gh"])
print(b)

['1' '23' '45' 'gh']


In [18]:
b.dtype

dtype('<U11')

In [19]:

k1 = [1,"234",89.23,"string"]
c = np.array(k1)
print(c)

['1' '234' '89.23' 'string']


In [20]:
np.arange(1,10,2)

array([1, 3, 5, 7, 9])

In [21]:
d=np.arange(1,20,3)
print(d)

[ 1  4  7 10 13 16 19]



## ndarray Properties:
#### .ndim
-        returns no of dimensions of an array
#### .shape
-        returns the no of rows and columns
#### .size
-        returns the size of an array
#### .dtype
-        we can specify the dtype like numpy.int32, numpy.int16 and numpy.float64
-        we can know the existing dtype
#### .itemsize
-        returns the size in bytes of each element in an array

In [22]:
# append
e=[1,2,3]
f=np.append(e,[4,5,6])
print(f)

[1 2 3 4 5 6]


In [35]:
z=np.array([1,2,3])
print(np.append(z,[4,5,6]))

[1 2 3 4 5 6]


In [23]:
# linspace     # creating an array with in the given range with required number of elements
a=np.linspace(1,10,10)
print(a)

[ 1.  2.  3.  4.  5.  6.  7.  8.  9. 10.]


In [24]:
a=np.linspace(1,2,20)
print(a)

[1.         1.05263158 1.10526316 1.15789474 1.21052632 1.26315789
 1.31578947 1.36842105 1.42105263 1.47368421 1.52631579 1.57894737
 1.63157895 1.68421053 1.73684211 1.78947368 1.84210526 1.89473684
 1.94736842 2.        ]


In [28]:
b=np.logspace(1,10,20)
print(b)

[1.00000000e+01 2.97635144e+01 8.85866790e+01 2.63665090e+02
 7.84759970e+02 2.33572147e+03 6.95192796e+03 2.06913808e+04
 6.15848211e+04 1.83298071e+05 5.45559478e+05 1.62377674e+06
 4.83293024e+06 1.43844989e+07 4.28133240e+07 1.27427499e+08
 3.79269019e+08 1.12883789e+09 3.35981829e+09 1.00000000e+10]


In [29]:
c=np.full(10,"abc")     # repeating required no of times with given value
c

array(['abc', 'abc', 'abc', 'abc', 'abc', 'abc', 'abc', 'abc', 'abc',
       'abc'], dtype='<U3')

In [31]:
s=np.zeros(10)   # fills an array with 0s by requires no of times
s

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [32]:
d=np.ones(20)
print(d)

[1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]


In [38]:
# 2d array
a=np.array([[1,2,3],[4,5,6],[7,8,9]])
print(a.ndim)
print(a.shape)
print(a.dtype)
print(a.size)
print(a.nbytes)
print(a.itemsize)

2
(3, 3)
int32
9
36
4


In [41]:
def hello():
    print("good morning archana")
print("hello madam")
hello()

hello madam
good morning archana


In [42]:
print(a)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [52]:
b=np.array([
    [
        [1,2,3],
        [4,5,6]
    ],
    [
        [7,8,9],
        [10,11,12]
    ]
            ])
print(b)
print(b.ndim)
print(b.shape)

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]
3
(2, 2, 3)


In [53]:
print(a)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [54]:
a

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [55]:
ma = np.array([1,2,3,4,5,6,7,8,9,10,11,12],ndmin=3) # returns ndim
ma

array([[[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12]]])

In [56]:
ma = np.array([1,2,3,4,5,6,7,8,9,10,11,12],ndmin=2)
ma

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12]])

In [59]:
e

[1, 2, 3]

In [60]:
e[0]

1

In [61]:
e[2]

3

In [62]:
a


array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [63]:
a[2][1]

8

In [64]:
a[1][1]

5

In [65]:
b

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [66]:
b[1][0][2]

9

In [70]:
b[0][1][2]

6

In [71]:
a

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [73]:
a[[0,1,2],[1,2,1]] #a[(0,1),(1,2),(2,1)]



array([2, 6, 8])

In [74]:
b

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [75]:
b[[0,0,1,1],[0,1,0,1],[1,2,1,2]]  #b[(0,0,1),(0,1,2),(1,0,1),(1,1,2)]

array([ 2,  6,  8, 12])

In [76]:
b[(1,1,2)]

12

In [78]:
b[0]

array([[1, 2, 3],
       [4, 5, 6]])

In [79]:
b[1]

array([[ 7,  8,  9],
       [10, 11, 12]])